swagger: "2.0"
info:
  title: Zava Inventory
  description: >-
    This MCP Server will work with Streamable HTTP and is meant to work with
    Microsoft Copilot Studio
  version: 1.0.0
host: { replace-with-dev-tunnel-URL }
basePath: /
schemes:
  - https
consumes: []
produces: []
definitions:
  QueryRequest:
    type: object
    properties:
      jsonrpc:
        type: string
      id:
        type: string
      method:
        type: string
      params:
        type: object
      result:
        type: object
      error:
        type: object
  QueryResponse:
    type: object
    properties:
      jsonrpc:
        type: string
      id:
        type: string
      method:
        type: string
      params:
        type: object
      result:
        type: object
      error:
        type: object
paths:
  /mcp:
    post:
      summary: Zava Inventory MCP
      responses:
        "200":
          description: Immediate Response
          schema:
            $ref: "#/definitions/QueryResponse"
        "201":
          description: Created and will follow callback
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: ZavaInventoryMCP
      description: >-
        This MCP Server helps Zava employees to learn more about stores,
        products & inventory.
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: Authorization
security:
  - api_key: []
tags: []
